version: "3"
services:
  robo3t:
    #tty: true
    #command:  bash
    container_name: robo3t
    volumes:
      - ./config:/config
      - ./output:/output
    build: .
    ports:
      - "5800:5800"
      - "5900:5900"